FROM golang:1.23-alpine AS build
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-s -w' -o bin/helm-wrapper


FROM scratch

ENV GIN_MODE=release

#COPY config-example.yaml  /config.yaml
COPY --from=build /app/bin/helm-wrapper /helm-wrapper

ENTRYPOINT [ "/helm-wrapper" ]
