FROM golang:1.23-alpine AS build
WORKDIR /app
COPY . .
RUN make build


FROM scratch

ENV GIN_MODE=release

#COPY config-example.yaml  /config.yaml
COPY --from=build /app/bin/helm-wrapper /helm-wrapper

ENTRYPOINT [ "/helm-wrapper" ]
